### ISSUE TITLE
Possible typo/obsolete code in daostorm_3d/

### ISSUE THREAD

**Issue by pskeshu** [ZhuangLab/storm-analysis#11]
Forgive me if I misread the code.

`daostorm_3d/zfit_analysis.py` calls `zFitting` in line 29 and 30 from `daostorm_3d/mufit_analysis.py`, where there is no function called `zFitting`. 

Same with driftCorrection. Is this a typo?

I think `zFitting` is located at `sa_utilities/std_analysis.py`, if at all `zfit_analysis` is still used or requires it.

Also, the import statement in line 10 in `daostorm_3d/zfit_analysis.py` tries to import from `storm_analysis.library`, instead of `sa_library`.

**Comment by HazenBabcock** [comment]
Thank you for the report. 

Yes this code is obsolete and should probably be deleted. It existed so that you could redo z fitting and drift correction without also having to redo peak finding and fitting. However this is no longer necessary as the analysis is now "smart" enough that it will skip the finding and fitting steps if it sees that they have already been done.

**Comment by HazenBabcock** [comment]
This should be fixed now. If ever do just want to redo z-fitting you can use `sa_utilities.fitz_c`.
