### ISSUE TITLE
how to make it work on my computer

### ISSUE THREAD

**Issue by ChangShuaibin** [ZhuangLab/storm-analysis#31]
Hi, I want to use the storm_analysis codes in my own computer, I think I have to compile those C files into DLL, but I have trouble in compiling them. For example, when I try to compile multi_fit.c, after I write #define MULTI_FIT_API __declspec(dllexport) on the beginning of the .h file and put MULTI_FIT_API before all the functions I want to export, I got an ERROR:"unresolved external symbol void __cdecldposv(char*,int*,int*,double*,int*,double*,int*,int*) in file multi_fit.obj". Usually such error occurs when you use a function before declaring it and I know how to fix it. But this time the error occurs in .obj file and I have no idea how to fix it. As you can see I'm using visual studio to compile the files.
So my question is,  first, is it right in th every beginning that I have to compile the .c files in order to make the code work? 
Second, if yes, how do you compile all those .c files. Can you please help me to solve that? Thanks a lot.

**Comment by HazenBabcock** [comment]
A few options depending on what you are trying to do:

1. Just use the wheels for Windows (64bit), which include pre-compiled DLLs. Instructions are here:
http://storm-analysis.readthedocs.io/en/latest/install.html#installing-using-wheels

2. Do a "source" installation. In this case you'll need to compile the DLLs yourself.
http://storm-analysis.readthedocs.io/en/latest/install.html#using-setup-py

The idea at least is that you will do this using the SCONs build system rather than trying do it yourself by hand. I've only done this using the mingw gcc compiler, but it should also work with Visual Studio. I think the command would be something like:
```
$ cd storm-analysis
$ C:\path\to\scons.bat -Q compiler=msvc
$ python setup.py install
```
On Windows scons.bat is usually in the `c:\python27\scripts` directory (pretty sure).

3. If you are trying to use the .c files in another C/C++ project then you will need to have the `storm-analysis/storm_analysis/c_libraries` in directory your path, or you will need to provide your own versions of LAPACK/BLAS, FFTW and possibly some of the other libraries in this directory.

In particular the error message you are seeing is (I think) the linker trying to tell you that it cannot find the LAPACK/BLAS function `dposv`. Yes normally you'd hit this problem when compiling, but because of how we've included this library in `storm-analysis` you don't see this error until the linking step.

**Comment by ChangShuaibin** [comment]
Thanks. I'll try the wheel.   
  

  
  

  
  
>

**Comment by HazenBabcock** [comment]
All good I assume.
