### ISSUE TITLE
Re-analyzing a movie without tracking

### ISSUE THREAD

**Issue by GayatriChandran** [ZhuangLab/storm-analysis#45]
I analyzed a movie using 3d daostorm with tracking, and then wanted to see what the image looks like without tracking. Can I do this without running `mFit.analyze()` all over again ? I thought it could find an existing file, and just skip the tracking part ?

**Comment by HazenBabcock** [comment]
You don't need to re-analyze anything. The HDF5 file has both the localizations and the tracking results. If you did tracking but you want `sa_utilities/hdf5_to_image.py` to make an image from the localizations then some hacking is required. I'd suggest making a personal copy and then changing the `if h5.hasTracks():` statements to `if False:` so that your version always makes the image from the localizations.

**Comment by GayatriChandran** [comment]
Ok, thanks !
